const places=[['Hannover',52.3759,9.732],['Langenhagen',52.447,9.743],['Garbsen',52.426,9.6],['Wunstorf',52.423,9.427],['Neustadt',52.505,9.462],['Burgwedel',52.5,9.863],['Lehrte',52.375,9.98],['Burgdorf',52.447,10.006],['Laatzen',52.315,9.797],['Barsinghausen',52.3,9.46],['Springe',52.208,9.552],['Seelze',52.397,9.598],['Wedemark',52.545,9.733],['Isernhagen',52.48,9.84],['Ronnenberg',52.319,9.655],['Hemmingen',52.322,9.742],['Pattensen',52.265,9.768],['Gehrden',52.313,9.6],['Wennigsen',52.275,9.57],['Uetze',52.465,10.205]].map(([name,lat,lon])=>({name,lat,lon}));
const label=c=>({0:'Klar',1:'Überwiegend klar',2:'Leicht bewölkt',3:'Bedeckt',45:'Nebel',48:'Nebel',51:'Leichter Nieselregen',53:'Nieselregen',55:'Starker Nieselregen',61:'Leichter Regen',63:'Regen',65:'Starker Regen',71:'Leichter Schneefall',73:'Schneefall',75:'Starker Schneefall',80:'Regenschauer',81:'Regenschauer',82:'Starke Regenschauer',95:'Gewitter',96:'Gewitter mit Hagel',99:'Starkes Gewitter'}[c]||'Wechselhaft');
const icon=c=>({0:'☀',1:'◐',2:'☁',3:'☁',45:'≋',48:'≋',51:'⌁',53:'⌁',55:'≋',61:'◒',63:'◒',65:'◒',71:'❄',73:'❄',75:'❄',80:'◒',81:'◒',82:'◒',95:'ϟ',96:'ϟ',99:'ϟ'}[c]||'•');
const rain=c=>[51,53,55,61,63,65,71,73,75,80,81,82].includes(c),storm=c=>[95,96,99].includes(c);
let data=[],selected=0,offset=0,map,markers=[],radarFrames=[],radarIndex=0,warningCount=0;
const app=document.getElementById('root');
app.innerHTML=`<div class="site"><header><a class="wordmark" href="#top">HANNOVER <em>WETTER</em></a><div class="nav"><a href="#radar">Radar</a><a href="#prognose">Prognose</a><a href="#region">Region</a></div><div class="live"><span></span><b id="clock">LIVE</b></div></header><main id="top"><section class="hero"><div class="heroCopy"><div><div class="eyebrow">REGION · LIVE · 20 ORTE</div><h1>Das Wetter<br><i>vor deiner Tür.</i></h1><p>Eine visuelle Wetterkarte für Hannover und die Region. Live-Daten, Radar, Prognose und Wetterverlauf an einem Ort.</p></div><div class="current"><div class="place" id="place">Hannover</div><div class="temp" id="temp">—°</div><div class="cond" id="cond">Wetter wird geladen</div><div class="meta"><span>Gefühlt <b id="feel">—°</b></span><span>Wind <b id="wind">— km/h</b></span><span>Feuchte <b id="hum">—%</b></span><span>Regen <b id="rain">—%</b></span></div></div></div><div class="visual"><canvas id="scene" class="sceneCanvas"></canvas><div class="weatherOrb"><span id="bigIcon">☀</span></div><div class="visualTop"><span id="visualCond">Atmosphäre</span><span id="coords">52°23′N · 9°44′E</span></div><div class="visualData"><div><small>WIND</small><b id="gust">—</b><span id="dir">—</span></div><div><small>LUFT</small><b id="pressure">—</b><span>hPa</span></div><div><small>UV</small><b id="uv">—</b><span>Index</span></div></div><div class="visualBottom"><span>HANNOVER</span><span>OPEN-METEO</span></div></div></section>
<section class="ticker"><div><b id="tickerTemp">—°</b><span>aktuell</span></div><div><b id="tickerHigh">—°</b><span>heute max.</span></div><div><b id="tickerRain">—%</b><span>Regenchance</span></div><div><b id="tickerSun">—</b><span>Sonnenuntergang</span></div><div class="tickerWarn"><b id="tickerWarn">0</b><span>DWD Hinweise</span></div></section>
<section class="radarSection" id="radar"><div class="sectionTitle"><span>01 · RADAR</span><h2>Was gerade auf Hannover zukommt.</h2><p>Regen · live</p></div><div class="radarFrame"><div id="map" class="map"></div><div class="radarGlow"></div><div class="radarHud"><div><strong id="radarTime">RADAR · LADE</strong><span>10-MINUTEN-TAKT</span></div><button id="radarPlay">▶</button></div><div class="mapLegend" id="legend">20 Orte · Live</div><div class="radarCredit">Weather data by RainViewer · © OpenStreetMap</div></div><div class="radarControls"><div id="radarSteps"></div><input id="radarRange" type="range" min="0" max="0" value="0"></div></section>
<section class="dashboard"><div class="dashboardLead"><span>02 · JETZT</span><h2>Die Lage<br><i>in Hannover.</i></h2><p id="summary">Die aktuellen Messwerte werden geladen.</p><div class="miniStats"><div><span>TAUPUNKT</span><b id="dew">—°</b></div><div><span>BEWÖLKUNG</span><b id="cloud">—%</b></div><div><span>NIEDERSCHLAG</span><b id="precip">— mm</b></div></div></div><div class="windCard"><div class="compass"><span>N</span><span>O</span><span>S</span><span>W</span><i id="needle"></i></div><div><small>WINDRICHTUNG</small><b id="windDir">—°</b><span id="windText">—</span></div></div><div class="sunCard"><div class="sunTrack"><i id="sunDot"></i></div><div class="sunTimes"><div><small>AUFGANG</small><b id="sunrise">—</b></div><div><small>UNTERGANG</small><b id="sunset">—</b></div></div><p id="daylight">— Stunden Tageslicht</p></div></section>
<section class="forecast" id="prognose"><div class="sectionTitle"><span>03 · PROGNOSE</span><h2>Die nächsten 24 Stunden.</h2><p id="forecastPlace">Hannover</p></div><div class="chartCard"><div class="chart" id="chart"></div><div class="hours" id="hours"></div><div class="chartFoot"><span>Temperatur</span><span>Regenwahrscheinlichkeit</span><input id="range" min="0" max="6" value="0" type="range"></div></div></section>
<section class="days"><div class="sectionTitle"><span>04 · AUSBLICK</span><h2>Die Woche in einem Blick.</h2></div><div class="dayGrid" id="days"></div></section>
<section class="region" id="region"><div class="sectionTitle"><span>05 · REGION</span><h2>20 Orte. Eine Wetterlage.</h2><p>Tippen zum Wechseln</p></div><div class="placeGrid" id="places"></div></section>
<section class="warnings"><div class="sectionTitle"><span>06 · HINWEISE</span><h2>Was du heute wissen solltest.</h2></div><div class="warningGrid"><div class="warningMain" id="warningMain"><span class="warningIcon">✓</span><div><small>DWD · AKTUELL</small><h3>Keine Warnung für Hannover erkannt.</h3><p>Die offiziellen DWD-Hinweise werden automatisch geprüft.</p></div></div><div class="sourceCard"><b>DATEN</b><p>Open-Meteo<br>DWD Hinweise<br>RainViewer Radar<br>OpenStreetMap</p></div></div></section></main><footer><strong>HANNOVER WETTER</strong><span>Automatische Aktualisierung · 5 Minuten</span><a href="https://www.rainviewer.com/" target="_blank" rel="noreferrer">RainViewer</a></footer></div>`;
const $=id=>document.getElementById(id);
function degDir(d){return ['N','NO','O','SO','S','SW','W','NW'][Math.round(d/45)%8]||'—'}
function formatTime(v){return v?new Date(v).toLocaleTimeString('de-DE',{hour:'2-digit',minute:'2-digit'}):'—'}
function render(){const w=data[selected],c=w?.current;if(!c)return;const d=w.daily||{};const h=w.hourly||{};const p=places[selected];$('place').textContent=p.name;$('forecastPlace').textContent=p.name;$('temp').textContent=Math.round(c.temperature_2m)+'°';$('cond').textContent=label(c.weather_code);$('visualCond').textContent=label(c.weather_code);$('bigIcon').textContent=icon(c.weather_code);$('feel').textContent=Math.round(c.apparent_temperature)+'°';$('wind').textContent=Math.round(c.wind_speed_10m)+' km/h';$('hum').textContent=Math.round(c.relative_humidity_2m)+'%';$('rain').textContent=(h.precipitation_probability?.[currentHour(h)]??0)+'%';$('gust').textContent=Math.round(c.wind_gusts_10m||c.wind_speed_10m)+' km/h';$('dir').textContent=degDir(c.wind_direction_10m||0);$('pressure').textContent=Math.round(c.pressure_msl||0);$('uv').textContent=(d.uv_index_max?.[0]??0).toFixed(1);$('dew').textContent=Math.round(c.dew_point_2m??0)+'°';$('cloud').textContent=Math.round(c.cloud_cover??0)+'%';$('precip').textContent=(c.precipitation??0).toFixed(1)+' mm';$('windDir').textContent=Math.round(c.wind_direction_10m||0)+'°';$('windText').textContent=degDir(c.wind_direction_10m||0)+' · '+Math.round(c.wind_speed_10m)+' km/h';$('needle').style.transform=`rotate(${c.wind_direction_10m||0}deg)`;$('tickerTemp').textContent=Math.round(c.temperature_2m)+'°';$('tickerHigh').textContent=(d.temperature_2m_max?.[0]!=null?Math.round(d.temperature_2m_max[0]):'—')+'°';$('tickerRain').textContent=(d.precipitation_probability_max?.[0]??0)+'%';$('tickerSun').textContent=formatTime(d.sunset?.[0]);$('clock').textContent='LIVE · '+new Date().toLocaleTimeString('de-DE',{hour:'2-digit',minute:'2-digit'});$('coords').textContent=p.lat.toFixed(2)+'°N · '+p.lon.toFixed(2)+'°E';$('summary').textContent=summary(c,d,h);$('sunrise').textContent=formatTime(d.sunrise?.[0]);$('sunset').textContent=formatTime(d.sunset?.[0]);$('daylight').textContent=daylight(d.daylight_duration?.[0]);setSun(d);renderPlaces();renderHours();renderDays();drawScene(c.weather_code);updateMarkers();}
function currentHour(h){if(!h.time)return 0;const n=Date.now(),i=h.time.findIndex(t=>new Date(t).getTime()>=n);return i<0?0:i}
function summary(c,d,h){const rainText=(h.precipitation_probability?.slice(0,6)||[]).some(v=>v>=60)?'Regen ist in den nächsten Stunden wahrscheinlich. ':'Die nächsten Stunden bleiben überwiegend trocken. ';const temp=d.temperature_2m_max?.[0];return rainText+'Aktuell '+Math.round(c.temperature_2m)+'° bei '+label(c.weather_code).toLowerCase()+'. Heute werden bis zu '+(temp!=null?Math.round(temp):'—')+'° erwartet.'}
function daylight(sec){return sec?((sec/3600).toFixed(1).replace('.',',')+' Stunden Tageslicht'):'— Stunden Tageslicht'}
function setSun(d){const sunrise=d.sunrise?.[0]?new Date(d.sunrise[0]).getTime():0,sunset=d.sunset?.[0]?new Date(d.sunset[0]).getTime():0,n=Date.now();let x=sunset>sunrise?Math.max(0,Math.min(1,(n-sunrise)/(sunset-sunrise))):.5;$('sunDot').style.left=(x*100)+'%'}
function renderPlaces(){$('places').innerHTML=places.map((p,i)=>{const c=data[i]?.current;return `<button class="placeCard ${i===selected?'active':''}" data-i="${i}"><span>${String(i+1).padStart(2,'0')}</span><strong>${p.name}</strong><b>${c?Math.round(c.temperature_2m)+'°':'—'}</b><small>${c?icon(c.weather_code)+' '+label(c.weather_code):'—'}</small></button>`}).join('');document.querySelectorAll('.placeCard').forEach(b=>b.onclick=()=>{selected=+b.dataset.i;render();window.scrollTo({top:0,behavior:'smooth'})})}
function renderHours(){const h=data[selected]?.hourly;if(!h)return;let start=currentHour(h);const arr=Array.from({length:12},(_,k)=>Math.min(start+offset+k,h.time.length-1));const vals=arr.map(i=>h.temperature_2m[i]);const min=Math.min(...vals)-2,max=Math.max(...vals)+2;const chart=$('chart');chart.innerHTML=arr.map((i,k)=>{const y=10+(max-h.temperature_2m[i])/(max-min)*70;return `<i class="chartDot" style="left:${(k/(arr.length-1))*100}%;top:${y}%"><b>${Math.round(h.temperature_2m[i])}°</b></i>`}).join('');$('hours').innerHTML=arr.map((i,k)=>{const t=new Date(h.time[i]);const prob=h.precipitation_probability[i]||0;return `<div class="hour"><small>${k===0?'JETZT':t.toLocaleTimeString('de-DE',{hour:'2-digit',minute:'2-digit'})}</small><strong>${Math.round(h.temperature_2m[i])}°</strong><span>${prob}% Regen</span><i style="height:${Math.max(6,prob*.7)}%"></i></div>`}).join('')}
function renderDays(){const d=data[selected]?.daily;if(!d?.time)return;$('days').innerHTML=d.time.slice(0,7).map((day,i)=>{const date=new Date(day+'T12:00:00');const name=i===0?'HEUTE':date.toLocaleDateString('de-DE',{weekday:'short'}).toUpperCase();return `<article class="day"><small>${name}</small><div class="dayIcon">${icon(d.weather_code[i])}</div><b>${Math.round(d.temperature_2m_max[i])}°</b><span>${Math.round(d.temperature_2m_min[i])}°</span><em>${d.precipitation_probability_max[i]||0}%</em></article>`}).join('')}
$('range').oninput=e=>{offset=+e.target.value;renderHours()};
async function load(){try{const lat=places.map(p=>p.lat).join(','),lon=places.map(p=>p.lon).join(','),u=`https://api.open-meteo.com/v1/forecast?latitude=${lat}&longitude=${lon}&current=temperature_2m,apparent_temperature,precipitation,weather_code,wind_speed_10m,wind_direction_10m,wind_gusts_10m,relative_humidity_2m,dew_point_2m,pressure_msl,cloud_cover&hourly=temperature_2m,precipitation_probability,weather_code&daily=weather_code,temperature_2m_max,temperature_2m_min,precipitation_probability_max,sunrise,sunset,daylight_duration,uv_index_max&forecast_days=7&timezone=Europe%2FBerlin`;const r=await fetch(u);if(!r.ok)throw Error('Wetterdaten konnten nicht geladen werden.');data=await r.json();render()}catch(e){$('legend').textContent='Wetterdaten vorübergehend nicht verfügbar';console.error(e)}}
async function loadRadar(){try{const r=await fetch('https://api.rainviewer.com/public/weather-maps.json');const j=await r.json();radarFrames=j.radar?.past||[];if(!radarFrames.length)return;$('radarRange').max=radarFrames.length-1;radarIndex=radarFrames.length-1;$('radarRange').value=radarIndex;renderRadarSteps();setRadar(radarIndex)}catch(e){$('radarTime').textContent='RADAR · NICHT VERFÜGBAR';console.warn(e)}}
function radarUrl(frame){return `https://tilecache.rainviewer.com${frame.path}/256/{z}/{x}/{y}/2/1_1.png`}
function setRadar(i){if(!map||!radarFrames[i])return;radarIndex=i;const frame=radarFrames[i],tiles=radarUrl(frame);if(map.getLayer('rain'))map.removeLayer('rain');if(map.getSource('rain'))map.removeSource('rain');map.addSource('rain',{type:'raster',tiles:[tiles],tileSize:256});map.addLayer({id:'rain',type:'raster',source:'rain',paint:{'raster-opacity':.62,'raster-fade-duration':180}});$('radarRange').value=i;$('radarTime').textContent='RADAR · '+new Date(frame.time*1000).toLocaleTimeString('de-DE',{hour:'2-digit',minute:'2-digit'});document.querySelectorAll('.radarStep').forEach((b,n)=>b.classList.toggle('active',n===i))}
function renderRadarSteps(){const frames=radarFrames.slice(-7);$('radarSteps').innerHTML=frames.map((f,i)=>`<button class="radarStep ${i===frames.length-1?'active':''}" data-r="${radarFrames.indexOf(f)}">${new Date(f.time*1000).toLocaleTimeString('de-DE',{hour:'2-digit',minute:'2-digit'})}</button>`).join('');document.querySelectorAll('.radarStep').forEach(b=>b.onclick=()=>setRadar(+b.dataset.r))}
$('radarRange').oninput=e=>setRadar(+e.target.value);$('radarPlay').onclick=()=>{let i=radarIndex,run=true;$('radarPlay').textContent='Ⅱ';const timer=setInterval(()=>{if(!run){clearInterval(timer);return}i=(i+1)%radarFrames.length;setRadar(i)},700);setTimeout(()=>{run=false;$('radarPlay').textContent='▶'},Math.min(radarFrames.length*700,9000))};
async function loadWarnings(){try{const r=await fetch('https://www.dwd.de/DWD/warnungen/warnapp/json/warnings.json');const j=await r.json();const all=JSON.stringify(j);const hits=(all.match(/Hannover/gi)||[]).length;warningCount=hits?1:0;$('tickerWarn').textContent=warningCount;if(warningCount){$('warningMain').classList.add('hasWarning');$('warningMain').innerHTML='<span class="warningIcon">!</span><div><small>DWD · HINWEIS</small><h3>Aktuelle DWD-Information für die Region gefunden.</h3><p>Öffne die offiziellen Warnmeldungen für die genaue Lage und Gültigkeit.</p></div>'}}catch(e){$('tickerWarn').textContent='—';console.warn(e)}}
function drawScene(code){const c=$('scene'),x=c.getContext('2d');let ps=Array.from({length:150},()=>({x:Math.random(),y:Math.random(),s:.3+Math.random()*1.2}));function frame(){const w=c.clientWidth,h=c.clientHeight,d=devicePixelRatio||1;c.width=w*d;c.height=h*d;x.setTransform(d,0,0,d,0,0);const night=new Date().getHours()<7||new Date().getHours()>20;const g=x.createLinearGradient(0,0,0,h);g.addColorStop(0,night?'#111b32':rain(code)?'#b8e7f7':'#bceeff');g.addColorStop(.55,night?'#243d68':'#e8f8ff');g.addColorStop(1,night?'#0d172b':'#d5f0f9');x.fillStyle=g;x.fillRect(0,0,w,h);const glow=x.createRadialGradient(w*.72,h*.2,5,w*.72,h*.2,w*.5);glow.addColorStop(0,night?'rgba(215,245,107,.24)':'rgba(255,255,255,.7)');glow.addColorStop(1,'rgba(255,255,255,0)');x.fillStyle=glow;x.fillRect(0,0,w,h);x.fillStyle=night?'#101b30':'#a8d5e6';x.beginPath();x.moveTo(0,h*.74);for(let i=0;i<=14;i++)x.lineTo(w*i/14,h*(.7+Math.sin(i*1.4)*.035));x.lineTo(w,h);x.lineTo(0,h);x.fill();if(rain(code)){x.strokeStyle=night?'rgba(210,235,255,.28)':'rgba(35,105,145,.22)';ps.forEach(p=>{p.y+=p.s*.022;p.x-=p.s*.004;if(p.y>1){p.y=-.05;p.x=Math.random()}x.beginPath();x.moveTo(p.x*w,p.y*h);x.lineTo(p.x*w-5,p.y*h+20);x.stroke()})}else{ps.forEach(p=>{p.x=(p.x+p.s*.0003)%1;x.fillStyle=night?'rgba(255,255,255,.3)':'rgba(255,255,255,.45)';x.beginPath();x.arc(p.x*w,p.y*h,1.2,0,7);x.fill()})}if(storm(code)&&Math.random()<.025){x.fillStyle='rgba(255,255,255,.25)';x.fillRect(0,0,w,h)}requestAnimationFrame(frame)}frame()}
function initMap(){if(!window.maplibregl)return;map=new maplibregl.Map({container:'map',style:{version:8,sources:{osm:{type:'raster',tiles:['https://tile.openstreetmap.org/{z}/{x}/{y}.png'],tileSize:256,attribution:'© OpenStreetMap'}},layers:[{id:'osm',type:'raster',source:'osm',paint:{'raster-opacity':.68}}]},center:[9.73,52.39],zoom:9.35,dragRotate:false,scrollZoom:false,boxZoom:false,doubleClickZoom:false});map.addControl(new maplibregl.AttributionControl({compact:true}));map.on('load',()=>{updateMarkers();loadRadar()})}
function updateMarkers(){if(!map)return;markers.forEach(m=>m.remove());markers=[];places.forEach((p,i)=>{const el=document.createElement('button');el.className='map-pin '+(i===selected?'selected':'');const t=data[i]?.current.temperature_2m;el.innerHTML=`<span>${t!=null?Math.round(t)+'°':'—'}</span><i></i><b>${p.name}</b>`;el.onclick=()=>{selected=i;render()};markers.push(new maplibregl.Marker({element:el,anchor:'bottom'}).setLngLat([p.lon,p.lat]).addTo(map))})}
const s=document.createElement('link');s.rel='stylesheet';s.href='https://unpkg.com/maplibre-gl@5.6.0/dist/maplibre-gl.css';document.head.appendChild(s);const js=document.createElement('script');js.src='https://unpkg.com/maplibre-gl@5.6.0/dist/maplibre-gl.js';js.onload=()=>initMap();document.head.appendChild(js);load();loadWarnings();setInterval(load,300000);setInterval(loadWarnings,600000);