const PLACES=[['Hannover',52.3759,9.732],['Langenhagen',52.447,9.743],['Garbsen',52.426,9.6],['Wunstorf',52.423,9.427],['Neustadt',52.505,9.462],['Burgwedel',52.5,9.863],['Lehrte',52.375,9.98],['Laatzen',52.315,9.797],['Sehnde',52.313,9.969],['Barsinghausen',52.3,9.46],['Pattensen',52.265,9.768],['Springe',52.208,9.552],['Hemmingen',52.322,9.742],['Ronnenberg',52.319,9.655],['Gehrden',52.313,9.6],['Seelze',52.397,9.598],['Wedemark',52.545,9.733],['Isernhagen',52.48,9.84],['Wennigsen',52.275,9.57],['Uetze',52.465,10.205]].map(([name,lat,lon])=>({name,lat,lon}));
const WX={0:['Klar','☀'],1:['Überwiegend klar','◐'],2:['Leicht bewölkt','☁'],3:['Bedeckt','☁'],45:['Nebel','≋'],48:['Nebel','≋'],51:['Nieselregen','⌁'],53:['Nieselregen','⌁'],55:['Nieselregen','⌁'],61:['Leichter Regen','🌧'],63:['Regen','🌧'],65:['Starker Regen','🌧'],71:['Schnee','❄'],73:['Schnee','❄'],75:['Schnee','❄'],80:['Schauer','🌦'],81:['Schauer','🌦'],82:['Starke Schauer','🌧'],95:['Gewitter','ϟ'],96:['Gewitter','ϟ'],99:['Gewitter','ϟ']};
const IMAGES=[
'https://www.hannover.de/content/download/870509/file/Neues-Rathaus.jpg',
'https://www.hannover.de/var/storage/images/_aliases/alias_300x225px/media/01-data-neu/bilder/hmtg/kommunen/langenhagen/grafiken/neue-bult-4/1332012-2-ger-DE/Neue-Bult-4.jpg',
'https://www.hannover.de/var/storage/images/_aliases/alias_300x225px/media/01-data-neu/bilder/hmtg/kommunen/garbsen/grafiken/blauer-see/12542488-2-ger-DE/Blauer-See.jpg',
'https://www.hannover.de/var/storage/images/_aliases/alias_300x225px/media/01-data-neu/bilder/hmtg/sprachversion/teaser/festliches-wochenende-steinhude/6992384-2-ger-DE/Festliches-Wochenende-Steinhude.jpg',
'https://www.hannover.de/var/storage/images/_aliases/alias_300x225px/8/0/8/5/1325808-2-ger-DE/Neustadt-Landestrost-7273.jpg',
'https://www.hannover.de/var/storage/images/_aliases/alias_300x225px/media/01-data-neu/bilder/hmtg/kommunen/entdecke-deine-region/springhorstsee-burgwedel/15546757-1-ger-DE/Springhorstsee-Burgwedel.jpg',
'https://www.hannover.de/var/storage/images/_aliases/image_full/media/01-data-neu/bilder/hmtg/data-kommunen/bilder-kommunen/lehrte/panorama/willkommen-in-lehrte/7429388-1-ger-DE/Willkommen-in-Lehrte.jpg',
'https://www.hannover.de/var/storage/images/_aliases/alias_300x225px/5/7/9/6/21796975-2-ger-DE/350259d8f792-Park-der-Sinne.jpg',
'https://www.hannover.de/var/storage/images/_aliases/image_full/media/01-data-neu/bilder/hmtg/data-kommunen/bilder-kommunen/sehnde/panorama/willkommen-in-sehnde/7430556-1-ger-DE/Willkommen-in-Sehnde.jpg',
'https://www.hannover.de/var/storage/images/_aliases/alias_300x225px/media/01-data-neu/bilder/hmtg/kommunen/entdecke-deine-region/deisteralm-barsinghausen/15547393-1-ger-DE/Deisteralm-Barsinghausen.jpg',
'https://www.hannover.de/var/storage/images/_aliases/alias_300x225px/media/01-data-neu/bilder/bilder-region-hannover/naherholung/parks-und-g%C3%A4rten/fuchsbachpark-pattensen2/20017934-2-ger-DE/Fuchsbachpark-Pattensen.jpg',
'https://www.hannover.de/var/storage/images/_aliases/alias_300x225px/media/01-data-neu/bilder/hmtg/kommunen/springe/grafiken/innenstadt-springe-altes-rathaus/1314734-2-ger-DE/Innenstadt-Springe-Altes-Rathaus.jpg',
'https://www.hannover.de/var/storage/images/_aliases/alias_300x225px/media/01-data-neu/bilder/hmtg/kommunen/entdecke-deine-region/strandbad-hemmingen2/15547561-1-ger-DE/Strandbad-Hemmingen.jpg',
'https://www.hannover.de/var/storage/images/_aliases/alias_300x225px/sachlogische-struktur/hannover.de/leben-in-der-region-hannover/verwaltungen-kommunen/kommunen/ronnenberg/data_aktuell/grafiken/ronnenberg_kirche/1345192-1-ger-DE/Ronnenberg_Kirche1.jpg',
'https://www.hannover.de/var/storage/images/_aliases/alias_300x225px/media/01-data-neu/bilder/hmtg/data-kommunen/bilder-kommunen/gehrden/panorama/wilkommen-in-gehrden/7421069-1-ger-DE/Wilkommen-in-Gehrden.jpg',
'https://www.hannover.de/var/storage/images/_aliases/alias_300x225px/media/01-data-neu/bilder/hmtg/kommunen/entdecke-deine-region/yachthafen-seelze/15546305-1-ger-DE/Yachthafen-Seelze.jpg',
'https://www.hannover.de/var/storage/images/_aliases/alias_300x225px/sachlogische-struktur/hannover.de/leben-in-der-region-hannover/verwaltungen-kommunen/kommunen/wedemark/data_aktuell/grafiken/wedemark_pferde/1330059-1-ger-DE/Wedemark_Pferde1.jpg',
'https://www.hannover.de/var/storage/images/_aliases/alias_300x225px/media/01-data-neu/bilder/hmtg/kommunen/entdecke-deine-region/w%C3%B6hler-dusche-hof-isernhagen/15547225-1-ger-DE/W%C3%B6hler-Dusche-Hof-Isernhagen.jpg',
'https://www.hannover.de/var/storage/images/_aliases/alias_300x225px/media/01-data-neu/bilder/hmtg/kommunen/entdecke-deine-region/kloster-wennigsen/15547729-1-ger-DE/Kloster-Wennigsen.jpg',
'https://www.hannover.de/var/storage/images/_aliases/alias_300x225px/media/01-data-neu/bilder/hmtg/kommunen/entdecke-deine-region/wackerwinkel-uetze/15547057-1-ger-DE/Wackerwinkel-Uetze.jpg'];
const label=c=>WX[c]?.[0]||'Wechselhaft',icon=c=>WX[c]?.[1]||'•',time=s=>s?new Date(s).toLocaleTimeString('de-DE',{hour:'2-digit',minute:'2-digit'}):'—';const $=id=>document.getElementById(id);window.WEATHER_APP={PLACES,data:[]};
function shell(){$('app').innerHTML=`<div class="dash"><header class="nav"><div class="logo">HANNOVER <span>WETTER</span></div><nav class="navlinks"><a class="active" href="#top">HEUTE</a><a href="#radar">RADAR</a><a href="#hours">PROGNOSE</a><a href="#region">REGION</a><a href="#warnings">WARNUNGEN</a></nav><div class="menu">☰</div></header><section class="hero" id="top"><div class="heroTop"><div class="heroDate"><small id="date">HEUTE</small><b id="clock">--:--</b></div><div class="heroQuote">Gleicher<br>Himmel,<br>andere Geschichten.</div><div class="heroStatus"><small>Aktuell in Hannover</small><div class="row"><div><div class="heroTemp" id="heroTemp">—°</div><div class="heroCond" id="heroCond">Lade Wetterdaten…</div></div><div class="heroFacts"><span>◌ Gefühlt <b id="heroFeel">—°</b></span><span>♧ Luftfeuchte <b id="heroHum">—%</b></span><span>≋ Wind <b id="heroWind">— km/h</b></span><span id="heroDir">—</span></div></div></div><div class="heroHint"><b>Hannover heute.</b><br><span id="hint">Echte Live-Daten für Hannover und die Region.</span></div></div></section><section class="layout"><div><div class="panel rainAlert"><h2 id="rainTitle">Niederschlag im Blick</h2><p id="rainText">Die nächsten Stunden werden geladen.</p><div class="rainTimeline" id="rainBars"></div><div class="rainLabels"><span>Jetzt</span><span>+1h</span><span>+2h</span><span>+3h</span></div></div><div class="panel hoursPanel" id="hours"><div class="sectionTitle"><h3>Die nächsten Stunden</h3><span>Stündlich ›</span></div><div class="hourGrid" id="hourGrid"></div><div class="week" id="week"></div><div class="sunline"><div>☼ Sonnenaufgang <b id="sunrise">—</b></div><div>☼ Sonnenuntergang <b id="sunset">—</b></div><div>◷ Tageslänge <b id="daylight">—</b></div></div></div></div><div class="panel radarPanel" id="radar"><div class="radarHead"><b>RADAR</b><span>WOLKEN</span><span>TEMPERATUR</span><span>WIND</span><span>MEHR</span><strong style="margin-left:auto">DWD</strong><span>RainViewer</span></div><div id="map"></div><div class="radarFoot"><button id="radarPlay">▶</button><input id="radarRange" type="range" min="0" max="0" value="0"><span id="radarTime">RADAR · LIVE</span><div id="radarSteps" style="display:none"></div><div id="radarStatus" style="font-size:9px;opacity:.65">VERBINDE…</div></div></div></section><section id="region"><div class="regionHead"><h2>20 Orte. Eine Region.</h2><span>Live aktualisiert ›</span></div><div class="cards" id="cards"></div></section><section id="warnings" class="warn"><div><small>DWD · AKTUELL</small><h3 id="warnTitle">Warnlage wird geprüft</h3></div><div id="warnText">Offizielle Hinweise werden automatisch geprüft.</div></section><footer class="footer"><span>HANNOVER WETTER</span><span>ECHTE DATEN. ECHTE MOMENTE.</span><span>REGION HANNOVER</span></footer></div>`}
async function load(){const url=`https://api.open-meteo.com/v1/forecast?latitude=${PLACES.map(p=>p.lat).join(',')}&longitude=${PLACES.map(p=>p.lon).join(',')}&current=temperature_2m,apparent_temperature,precipitation,weather_code,wind_speed_10m,wind_direction_10m,relative_humidity_2m,is_day&hourly=temperature_2m,precipitation_probability,weather_code&daily=weather_code,temperature_2m_max,temperature_2m_min,precipitation_probability_max,sunrise,sunset,daylight_duration&timezone=Europe%2FBerlin&forecast_days=7`;const res=await fetch(url,{cache:'no-store'});if(!res.ok)throw Error('weather '+res.status);const data=await res.json();window.WEATHER_APP.data=data.map((d,i)=>({...d,place:PLACES[i]}));render(window.WEATHER_APP.data[0]);renderCards(window.WEATHER_APP.data);loadWarnings()}
function render(w){const c=w.current,d=w.daily,h=w.hourly,now=new Date();$('heroTemp').textContent=Math.round(c.temperature_2m)+'°';$('heroFeel').textContent=Math.round(c.apparent_temperature)+'°';$('heroHum').textContent=Math.round(c.relative_humidity_2m)+'%';$('heroWind').textContent=Math.round(c.wind_speed_10m)+' km/h';$('heroDir').textContent=windDir(c.wind_direction_10m);$('heroCond').textContent=label(c.weather_code);$('date').textContent=now.toLocaleDateString('de-DE',{weekday:'short',day:'2-digit',month:'short',year:'numeric'}).toUpperCase();$('clock').textContent=now.toLocaleTimeString('de-DE',{hour:'2-digit',minute:'2-digit'});$('hint').textContent=`${label(c.weather_code)} in Hannover. ${c.precipitation>0?'Aktuell fällt Niederschlag.':'Aktuell kein Niederschlag.'}`;$('sunrise').textContent=time(d.sunrise?.[0]);$('sunset').textContent=time(d.sunset?.[0]);const sec=Math.round(d.daylight_duration?.[0]||0);$('daylight').textContent=`${Math.floor(sec/3600)}h ${Math.round((sec%3600)/60)}min`;const idx=Math.max(0,h.time.findIndex(t=>new Date(t)>=now)),probs=h.precipitation_probability.slice(idx,idx+24),max=Math.max(...probs.slice(0,12),0);$('rainTitle').textContent=max>=60?'Regen zieht auf':max>=30?'Niederschlag möglich':'Heute bleibt es meist trocken';$('rainText').textContent=max>=30?`Die höchste Regenwahrscheinlichkeit in den nächsten Stunden liegt bei ${max}%.`:'Für die nächsten Stunden ist nur wenig Niederschlag zu erwarten.';$('hourGrid').innerHTML=h.time.slice(idx,idx+6).map((t,i)=>`<div class="hour"><small>${time(t)}</small><div class="weatherIcon">${icon(h.weather_code[idx+i])}</div><b>${Math.round(h.temperature_2m[idx+i])}°</b><small>${h.precipitation_probability[idx+i]||0}%</small></div>`).join('');$('week').innerHTML=d.time.map((t,i)=>`<div><small>${new Date(t+'T12:00:00').toLocaleDateString('de-DE',{weekday:'short'})}</small><div>${icon(d.weather_code[i])}</div><b>${Math.round(d.temperature_2m_max[i])}°</b><small>${Math.round(d.temperature_2m_min[i])}°</small></div>`).join('');$('rainBars').innerHTML=probs.map(v=>`<i style="--h:${Math.max(8,Math.min(100,v||0))}%"></i>`).join('')}
function renderCards(data){$('cards').innerHTML=data.map((w,i)=>{const img=IMAGES[i],pos=['50%','48%','54%','52%','50%'][i%5];return `<article class="placeCard" data-i="${i}"><div class="placeArt" style="--bg:url('${img}');background-position:${pos} center"><div class="psun"></div><div class="pcloud"></div><div class="caption">${w.place.name}</div></div><div class="placeMeta"><small>${String(i+1).padStart(2,'0')}</small><strong>${w.place.name}</strong><span class="temp">${Math.round(w.current.temperature_2m)}°</span><span class="cond">${label(w.current.weather_code).toUpperCase()}</span><span class="wind">Gefühlt ${Math.round(w.current.apparent_temperature)}° · ${Math.round(w.current.wind_speed_10m)} km/h</span></div></article>`}).join('');document.querySelectorAll('.placeCard').forEach(card=>card.onclick=()=>render(data[+card.dataset.i]))}
function windDir(d){if(d==null)return'—';return['N','NO','O','SO','S','SW','W','NW'][Math.round(d/45)%8]}
async function loadWarnings(){try{const r=await fetch('https://www.dwd.de/DWD/warnungen/warnapp/json/warnings.json',{cache:'no-store'});const text=await r.text();const names=[...text.matchAll(/"regionName"\s*:\s*"([^"]+)"/g)].map(x=>x[1]),hit=names.find(n=>/Hannover|Region Hannover/i.test(n));$('warnTitle').textContent=hit?'Aktive DWD-Warnung in der Region':'Keine aktive Warnung';$('warnText').textContent=hit?'DWD meldet aktuell eine Warnung für Hannover/Region Hannover.':'Aktuell keine passende DWD-Warnung gefunden.'}catch(e){$('warnTitle').textContent='DWD momentan nicht erreichbar';$('warnText').textContent='Die Wetterdaten laufen weiter; die Warnlage wird beim nächsten Update erneut geprüft.'}}
shell();load().catch(e=>{console.error(e);$('heroCond').textContent='Daten momentan nicht verfügbar'});setInterval(()=>load().catch(()=>{}),300000);