const PLACES=[
['Hannover',52.3759,9.732],['Langenhagen',52.447,9.743],['Garbsen',52.426,9.6],['Wunstorf',52.423,9.427],['Neustadt',52.505,9.462],['Burgwedel',52.5,9.863],['Lehrte',52.375,9.98],['Laatzen',52.315,9.797],['Sehnde',52.313,9.969],['Barsinghausen',52.3,9.46],['Pattensen',52.265,9.768],['Springe',52.208,9.552],['Hemmingen',52.322,9.742],['Ronnenberg',52.319,9.655],['Gehrden',52.313,9.6],['Seelze',52.397,9.598],['Wedemark',52.545,9.733],['Isernhagen',52.48,9.84],['Wennigsen',52.275,9.57],['Uetze',52.465,10.205]
].map(([name,lat,lon])=>({name,lat,lon}));
const WX={0:['Klar','☀'],1:['Überwiegend klar','◐'],2:['Leicht bewölkt','☁'],3:['Bedeckt','☁'],45:['Nebel','≋'],48:['Nebel','≋'],51:['Nieselregen','⌁'],53:['Nieselregen','⌁'],55:['Nieselregen','⌁'],61:['Leichter Regen','🌧'],63:['Regen','🌧'],65:['Starker Regen','🌧'],71:['Schnee','❄'],73:['Schnee','❄'],75:['Schnee','❄'],80:['Schauer','🌦'],81:['Schauer','🌦'],82:['Starke Schauer','🌧'],95:['Gewitter','ϟ'],96:['Gewitter','ϟ'],99:['Gewitter','ϟ']};
const IMAGES=[
'https://www.hannover.de/content/download/870509/file/Neues-Rathaus.jpg',
'https://www.hannover.de/var/storage/images/_aliases/image_full/media/01-data-neu/bilder/hmtg/kongress-stadt/locations/panorama/locations-hannover/flughafen-hannover-langenhagen/10784144-1-ger-DE/Flughafen-Hannover-Langenhagen.jpg',
'https://www.hannover.de/var/storage/images/_aliases/alias_300x225px/media/01-data-neu/bilder/hmtg/kommunen/garbsen/grafiken/blauer-see/12542488-2-ger-DE/Blauer-See.jpg',
'https://www.hannover.de/var/storage/images/_aliases/alias_300x225px/media/01-data-neu/bilder/hmtg/sprachversion/teaser/festliches-wochenende-steinhude/6992384-2-ger-DE/Festliches-Wochenende-Steinhude.jpg',
'https://www.hannover.de/var/storage/images/_aliases/alias_300x225px/8/0/8/5/1325808-2-ger-DE/Neustadt-Landestrost-7273.jpg',
'https://www.hannover.de/var/storage/images/_aliases/alias_300x225px/media/01-data-neu/bilder/hmtg/kommunen/entdecke-deine-region/springhorstsee-burgwedel/15546757-1-ger-DE/Springhorstsee-Burgwedel.jpg',
'https://www.hannover.de/var/storage/images/_aliases/image_full/media/01-data-neu/bilder/hmtg/data-kommunen/bilder-kommunen/lehrte/panorama/willkommen-in-lehrte/7429388-1-ger-DE/Willkommen-in-Lehrte.jpg',
'https://www.hannover.de/var/storage/images/_aliases/alias_300x225px/5/7/9/6/21796975-2-ger-DE/350259d8f792-Park-der-Sinne.jpg',
'https://www.hannover.de/var/storage/images/_aliases/image_full/media/01-data-neu/bilder/hmtg/data-kommunen/bilder-kommunen/sehnde/panorama/willkommen-in-sehnde/7430556-1-ger-DE/Willkommen-in-Sehnde.jpg',
'https://www.hannover.de/var/storage/images/_aliases/alias_300x225px/media/01-data-neu/bilder/hmtg/kommunen/entdecke-deine-region/deisteralm-barsinghausen/15547393-1-ger-DE/Deisteralm-Barsinghausen.jpg',
'https://www.hannover.de/var/storage/images/_aliases/alias_300x225px/media/01-data-neu/bilder/bilder-region-hannover/naherholung/parks-und-g%C3%A4rten/fuchsbachpark-pattensen2/20017934-2-ger-DE/Fuchsbachpark-Pattensen.jpg',
'https://www.hannover.de/var/storage/images/_aliases/alias_300x225px/media/01-data-neu/bilder/hmtg/kommunen/springe/grafiken/innenstadt-springe-altes-rathaus/1314734-2-ger-DE/Innenstadt-Springe-Altes-Rathaus.jpg',
'https://www.hannover.de/var/storage/images/_aliases/alias_300x225px/media/01-data-neu/bilder/hmtg/kommunen/entdecke-deine-region/strandbad-hemmingen2/15547561-1-ger-DE/Strandbad-Hemmingen.jpg',
'https://www.hannover.de/var/storage/images/_aliases/alias_300x225px/sachlogische-struktur/hannover.de/leben-in-der-region-hannover/verwaltungen-kommunen/kommunen/ronnenberg/data_aktuell/grafiken/ronnenberg_kirche/1345192-1-ger-DE/Ronnenberg_Kirche1.jpg',
'https://www.hannover.de/var/storage/images/_aliases/image_full/media/01-data-neu/bilder/hmtg/kommunen/entdecke-deine-region/ottomar-von-reden-park-gehrden/15547753-1-ger-DE/Ottomar-von-Reden-Park-Gehrden.jpg',
'https://www.hannover.de/var/storage/images/_aliases/alias_300x225px/media/01-data-neu/bilder/hmtg/kommunen/entdecke-deine-region/yachthafen-seelze/15546305-1-ger-DE/Yachthafen-Seelze.jpg',
'https://www.hannover.de/var/storage/images/_aliases/alias_300x225px/sachlogische-struktur/hannover.de/leben-in-der-region-hannover/verwaltungen-kommunen/kommunen/wedemark/data_aktuell/grafiken/wedemark_pferde/1330059-1-ger-DE/Wedemark_Pferde1.jpg',
'https://www.hannover.de/var/storage/images/_aliases/alias_300x225px/media/01-data-neu/bilder/hmtg/kommunen/entdecke-deine-region/w%C3%B6hler-dusche-hof-isernhagen/15547225-1-ger-DE/W%C3%B6hler-Dusche-Hof-Isernhagen.jpg',
'https://www.hannover.de/var/storage/images/_aliases/alias_300x225px/media/01-data-neu/bilder/hmtg/kommunen/entdecke-deine-region/kloster-wennigsen/15547729-1-ger-DE/Kloster-Wennigsen.jpg',
'https://www.hannover.de/var/storage/images/_aliases/alias_300x225px/media/01-data-neu/bilder/hmtg/kommunen/entdecke-deine-region/wackerwinkel-uetze/15547057-1-ger-DE/Wackerwinkel-Uetze.jpg'
];
const $=id=>document.getElementById(id);const label=c=>WX[c]?.[0]||'Wechselhaft';const icon=c=>WX[c]?.[1]||'•';const time=s=>s?new Date(s).toLocaleTimeString('de-DE',{hour:'2-digit',minute:'2-digit'}):'—';
window.WEATHER_APP={PLACES,data:[]};
function shell(){
$('app').innerHTML=`<div class="dash"><header class="nav"><div class="logo">HANNOVER <span>WETTER</span></div><nav><a class="active" href="#top">HEUTE</a><a href="#radar">RADAR</a><a href="#hours">PROGNOSE</a><a href="#region">REGION</a><a href="#warnings">WARNUNGEN</a></nav><div class="menu">☰</div></header>
<section class="hero" id="top"><div class="heroOverlay"></div><div class="heroTop"><div class="heroDate"><small id="date">HEUTE</small><b id="clock">--:--</b></div><div class="heroQuote"><strong id="heroPlace">HANNOVER</strong><span>Region Hannover</span></div><div class="heroStatus"><small id="heroStatus">Aktuell in Hannover</small><div class="row"><div><div class="heroTemp" id="heroTemp">—°</div><div class="heroCond" id="heroCond">Lade Wetterdaten …</div></div><div class="heroFacts"><span>Gefühlt <b id="heroFeel">—°</b></span><span>Luftfeuchte <b id="heroHum">—%</b></span><span>Wind <b id="heroWind">— km/h</b></span><span id="heroDir">—</span></div></div></div><div class="heroHint"><b id="hintTitle">Hannover heute.</b><br><span id="hint">Echte Live-Daten werden geladen.</span></div><div class="heroFx" id="heroFx"></div></div></section>
<section class="layout"><div><div class="panel rainAlert"><h2 id="rainTitle">Niederschlag im Blick</h2><p id="rainText">Die nächsten Stunden werden geladen.</p><div class="rainTimeline" id="rainBars"></div><div class="rainLabels"><span>Jetzt</span><span>+1h</span><span>+2h</span><span>+3h</span></div></div><div class="panel hoursPanel" id="hours"><div class="sectionTitle"><h3>Die nächsten Stunden</h3><span>Stündlich</span></div><div class="hourGrid" id="hourGrid"></div><div class="week" id="week"></div><div class="sunline"><div>☼ Sonnenaufgang <b id="sunrise">—</b></div><div>☼ Sonnenuntergang <b id="sunset">—</b></div><div>◷ Tageslänge <b id="daylight">—</b></div></div></div></div>
<div class="panel radarPanel" id="radar"><div class="radarHead"><b>RADAR</b><span>WOLKEN</span><span>TEMPERATUR</span><span>WIND</span><span>MEHR</span><strong>DWD</strong></div><div id="map"></div><div class="radarFoot"><button id="radarPlay">▶</button><input id="radarRange" type="range" min="0" max="0" value="0"><span id="radarTime">RADAR · LIVE</span><small id="radarStatus">VERBINDE …</small></div></div></section>
<section id="region"><div class="regionHead"><h2>20 Orte. Eine Region.</h2><span>Live aktualisiert</span></div><div class="cards" id="cards"></div></section>
<section id="warnings" class="warn"><div><small>DWD · AKTUELL</small><h3 id="warnTitle">Warnlage</h3></div><div id="warnText">Offizielle Hinweise werden geprüft.</div></section>
<footer class="footer"><span>HANNOVER WETTER</span><span>ECHTE DATEN. ECHTE MOMENTE.</span><span>REGION HANNOVER</span></footer></div>`;
}
function kind(code){if([95,96,99].includes(code))return'storm';if([71,73,75].includes(code))return'snow';if([51,53,55,61,63,65,80,81,82].includes(code))return'rain';if([45,48].includes(code))return'fog';if([2,3].includes(code))return'cloud';return'clear'}
function fx(type){if(type==='rain')return'<i class="rainFx"></i>'.repeat(12);if(type==='snow')return'<i class="snowFx">•</i>'.repeat(18);if(type==='storm')return'<i class="stormFx"></i>';if(type==='cloud')return'<i class="cloudFx"></i>';if(type==='fog')return'<i class="fogFx"></i>';return'<i class="sunFx"></i>'}
function select(w){const i=window.WEATHER_APP.data.indexOf(w),c=w.current,card=document.querySelector(`.placeCard[data-i="${i}"]`);if(!card)return;const image=card.dataset.image;const hero=document.querySelector('.hero');hero.style.backgroundImage=`url("${image}")`;hero.className='hero wx-'+kind(c.weather_code);$('heroPlace').textContent=w.place.name.toUpperCase();$('heroStatus').textContent=`Aktuell in ${w.place.name}`;$('hintTitle').textContent=`${w.place.name} heute.`;$('hint').textContent=`${label(c.weather_code)}. ${c.precipitation>0?'Aktuell fällt Niederschlag.':'Aktuell kein Niederschlag.'}`;$('heroTemp').textContent=Math.round(c.temperature_2m)+'°';$('heroFeel').textContent=Math.round(c.apparent_temperature)+'°';$('heroHum').textContent=Math.round(c.relative_humidity_2m)+'%';$('heroWind').textContent=Math.round(c.wind_speed_10m)+' km/h';$('heroDir').textContent=windDir(c.wind_direction_10m);$('heroCond').textContent=label(c.weather_code);$('heroFx').innerHTML=fx(kind(c.weather_code));document.querySelectorAll('.placeCard').forEach(x=>x.classList.remove('selected'));card.classList.add('selected');window.scrollTo({top:0,behavior:'smooth'})}
function render(w){const c=w.current,d=w.daily,h=w.hourly,now=new Date();$('date').textContent=now.toLocaleDateString('de-DE',{weekday:'short',day:'2-digit',month:'short',year:'numeric'}).toUpperCase();$('clock').textContent=now.toLocaleTimeString('de-DE',{hour:'2-digit',minute:'2-digit'});$('sunrise').textContent=time(d.sunrise?.[0]);$('sunset').textContent=time(d.sunset?.[0]);const sec=Math.round(d.daylight_duration?.[0]||0);$('daylight').textContent=`${Math.floor(sec/3600)}h ${Math.round(sec%3600/60)}min`;const idx=Math.max(0,h.time.findIndex(t=>new Date(t)>=now));const probs=h.precipitation_probability.slice(idx,idx+24);const max=Math.max(...probs.slice(0,12),0);$('rainTitle').textContent=max>=60?'Regen zieht auf':max>=30?'Niederschlag möglich':'Heute bleibt es meist trocken';$('rainText').textContent=max>=30?`Bis zu ${max}% Regenwahrscheinlichkeit in den nächsten Stunden.`:'Für die nächsten Stunden ist nur wenig Niederschlag zu erwarten.';$('hourGrid').innerHTML=h.time.slice(idx,idx+6).map((t,i)=>`<div class="hour"><small>${time(t)}</small><div class="weatherIcon">${icon(h.weather_code[idx+i])}</div><b>${Math.round(h.temperature_2m[idx+i])}°</b><small>${h.precipitation_probability[idx+i]||0}%</small></div>`).join('');$('week').innerHTML=d.time.map((t,i)=>`<div><small>${new Date(t+'T12:00:00').toLocaleDateString('de-DE',{weekday:'short'})}</small><div>${icon(d.weather_code[i])}</div><b>${Math.round(d.temperature_2m_max[i])}°</b><small>${Math.round(d.temperature_2m_min[i])}°</small></div>`).join('');$('rainBars').innerHTML=probs.slice(0,12).map(v=>`<i style="--h:${Math.max(8,Math.min(100,v||0))}%"></i>`).join('')}
function renderCards(data){$('cards').innerHTML=data.map((w,i)=>`<article class="placeCard" data-i="${i}" data-image="${IMAGES[i]}"><div class="placeArt"><div class="caption">${w.place.name}</div><div class="cardFx">${fx(kind(w.current.weather_code))}</div></div><div class="placeMeta"><small>${String(i+1).padStart(2,'0')}</small><strong>${w.place.name}</strong><span class="temp">${Math.round(w.current.temperature_2m)}°</span><span class="cond">${label(w.current.weather_code).toUpperCase()}</span><span class="wind">Gefühlt ${Math.round(w.current.apparent_temperature)}° · ${Math.round(w.current.wind_speed_10m)} km/h</span></div></article>`).join('');document.querySelectorAll('.placeCard').forEach(card=>card.addEventListener('click',()=>select(data[+card.dataset.i])));select(data[0])}
function windDir(deg){const dirs=['N','NO','O','SO','S','SW','W','NW'];return dirs[Math.round(deg/45)%8]}
async function load(){try{const url=`https://api.open-meteo.com/v1/forecast?latitude=${PLACES.map(p=>p.lat).join(',')}&longitude=${PLACES.map(p=>p.lon).join(',')}&current=temperature_2m,apparent_temperature,precipitation,weather_code,wind_speed_10m,wind_direction_10m,relative_humidity_2m&hourly=temperature_2m,precipitation_probability,weather_code&daily=weather_code,temperature_2m_max,temperature_2m_min,precipitation_probability_max,sunrise,sunset,daylight_duration&timezone=Europe%2FBerlin&forecast_days=7`;const res=await fetch(url,{cache:'no-store'});if(!res.ok)throw Error('Open-Meteo '+res.status);const raw=await res.json();const rows=Array.isArray(raw)?raw:[raw];if(rows.length!==PLACES.length)throw Error('Unerwartetes Datenformat');window.WEATHER_APP.data=rows.map((d,i)=>({...d,place:PLACES[i]}));render(window.WEATHER_APP.data[0]);renderCards(window.WEATHER_APP.data);loadWarnings()}catch(e){console.error(e);$('heroCond').textContent='Wetterdaten nicht verfügbar';$('hint').textContent='Die Wetterquelle konnte gerade nicht erreicht werden.';$('rainText').textContent='Bitte später erneut laden.'}}
function loadWarnings(){const s=document.createElement('script');s.src='https://www.dwd.de/DWD/warnungen/warnapp/json/warnings.json?callback=__dwd';window.__dwd=x=>{const list=Array.isArray(x)?x:Object.values(x||{}).flat();const hit=list.find(v=>/Hannover|Region Hannover/i.test(JSON.stringify(v)));$('warnTitle').textContent=hit?'DWD-Warnung aktiv':'Keine DWD-Warnung für Hannover';$('warnText').textContent=hit?'Offizielle Warninformationen liegen vor.':'Derzeit keine passende Warnung gefunden.'};s.onerror=()=>{$('warnTitle').textContent='DWD derzeit nicht erreichbar'};document.body.appendChild(s)}
shell();load();
