(()=>{const C={lat:52.39,lon:9.73,z:7},L=[['Hannover',52.3759,9.732],['Langenhagen',52.447,9.743],['Garbsen',52.426,9.6],['Wunstorf',52.423,9.427],['Neustadt',52.505,9.462],['Burgwedel',52.5,9.863],['Lehrte',52.375,9.98],['Burgdorf',52.447,10.006],['Laatzen',52.315,9.797],['Barsinghausen',52.3,9.46],['Springe',52.208,9.552],['Seelze',52.397,9.598],['Wedemark',52.545,9.733],['Isernhagen',52.48,9.84],['Ronnenberg',52.319,9.655],['Hemmingen',52.322,9.742],['Pattensen',52.265,9.768],['Gehrden',52.313,9.6],['Wennigsen',52.275,9.57],['Uetze',52.465,10.205]],F=[];let I=0,T;
const W=(lat,lon)=>{let n=2**C.z;return{x:(lon+180)/360*n*256,y:(1-Math.asinh(Math.tan(lat*Math.PI/180))/Math.PI)/2*n*256}};
function setup(){let m=document.querySelector('#map');if(!m)return;m.innerHTML='<div id="nr"><div id="nb"></div><img id="nrain"><div id="np"></div><div id="ns">RADAR · VERBINDE…</div></div>';let s=document.createElement('style');s.textContent='#map{position:absolute!important;inset:0!important;z-index:2!important;overflow:hidden!important;background:#dbe8ed!important}#nr{position:absolute;inset:0;overflow:hidden;background:#dbe8ed;z-index:3}#nb,#np{position:absolute;inset:0;transform:scale(1.7);transform-origin:50% 50%}#nb{z-index:1}#nrain{position:absolute;width:512px;height:512px;left:calc(50% - 256px);top:calc(50% - 256px);z-index:3;pointer-events:none;transform:scale(1.7);transform-origin:50% 50%}.nt{position:absolute;width:256px;height:256px}.pin{position:absolute;transform:translate(-50%,-100%);padding:5px 8px;border-radius:999px;background:rgba(246,243,236,.95);border:1px solid #bbb;font:500 8px DM Mono;white-space:nowrap;box-shadow:0 5px 15px #0002;z-index:4}.pin:before{content:"";display:inline-block;width:6px;height:6px;border-radius:50%;background:#3976ff;margin-right:5px}#np{z-index:4}#ns{position:absolute;right:15px;top:70px;z-index:6;padding:8px 10px;background:#f6f3ec;border:1px solid #ccd;font:500 7px DM Mono;letter-spacing:1px}.radarGlow{display:none!important}@media(min-width:800px){#nb,#np,#nrain{transform:scale(1.35)}}@media(max-width:700px){.pin{width:10px;height:10px;padding:0;border-radius:50%;font-size:0;background:#f6f3ec}.pin:before{width:6px;height:6px;margin:2px}.pin:first-child{background:#ff6b35}.pin:first-child:before{background:#fff}}';document.head.appendChild(s);base();pins();waitControls()}
function base(){let e=document.querySelector('#nb'),c=W(C.lat,C.lon),b=document.querySelector('#map').getBoundingClientRect(),tx=Math.floor(c.x/256),ty=Math.floor(c.y/256),rx=Math.ceil(b.width/512)+3,ry=Math.ceil(b.height/512)+3;for(let x=-rx;x<=rx;x++)for(let y=-ry;y<=ry;y++){let q=tx+x,r=ty+y;if(q<0||r<0||q>=2**C.z||r>=2**C.z)continue;let i=document.createElement('img');i.className='nt';i.src=`https://tile.openstreetmap.org/${C.z}/${q}/${r}.png`;i.style.left=`calc(50% + ${q*256-c.x}px)`;i.style.top=`calc(50% + ${r*256-c.y}px)`;e.appendChild(i)}}
function pins(){let e=document.querySelector('#np'),c=W(C.lat,C.lon);L.forEach((p,i)=>{let q=W(p[1],p[2]),d=document.createElement('div');d.className='pin';d.textContent=p[0];d.style.left=`calc(50% + ${q.x-c.x}px)`;d.style.top=`calc(50% + ${q.y-c.y}px)`;if(!i)d.style.borderColor='#ff6b35';e.appendChild(d)})}
function waitControls(){if(document.querySelector('#radarRange')&&document.querySelector('#radarPlay')&&document.querySelector('#radarSteps'))radar();else setTimeout(waitControls,100)}
async function radar(){try{let r=await fetch('https://api.rainviewer.com/public/weather-maps.json',{cache:'no-store'});if(!r.ok)throw new Error('RainViewer API '+r.status);let j=await r.json();F=j.radar?.past||[];if(!F.length)throw new Error('Keine Radarframes');I=F.length-1;let a=document.querySelector('#radarRange');a.max=I;a.value=I;a.oninput=()=>{I=+a.value;show()};document.querySelector('#radarPlay').onclick=play;document.querySelector('#radarSteps').innerHTML=F.slice(-7).map(f=>`<button class="radarStep" data-i="${F.indexOf(f)}">${new Date(f.time*1000).toLocaleTimeString('de-DE',{hour:'2-digit',minute:'2-digit'})}</button>`).join('');document.querySelectorAll('.radarStep').forEach(b=>b.onclick=()=>{I=+b.dataset.i;show()});show();document.querySelector('#ns').textContent='RADAR · LIVE'}catch(e){let n=document.querySelector('#ns');if(n)n.textContent='RADAR · FEHLER';console.warn('Radar',e)}}
function show(){let f=F[I];if(!f)return;let img=document.querySelector('#nrain');img.onload=()=>{document.querySelector('#ns').textContent='RADAR · LIVE'};img.onerror=()=>{document.querySelector('#ns').textContent='RADAR · KARTENEBENE FEHLT'};img.src=`https://tilecache.rainviewer.com${f.path}/512/${C.z}/${C.lat}/${C.lon}/2/1_1.png`;document.querySelector('#radarTime').textContent='RADAR · '+new Date(f.time*1000).toLocaleTimeString('de-DE',{hour:'2-digit',minute:'2-digit'});document.querySelectorAll('.radarStep').forEach(b=>b.classList.toggle('active',+b.dataset.i===I))}
function play(){clearInterval(T);let i=I;document.querySelector('#radarPlay').textContent='Ⅱ';T=setInterval(()=>{i=(i+1)%F.length;I=i;show()},800);setTimeout(()=>{clearInterval(T);document.querySelector('#radarPlay').textContent='▶'},Math.min(F.length*800,9000))}
new MutationObserver(ms=>ms.forEach(m=>m.addedNodes.forEach(n=>{if(n.tagName==='SCRIPT'&&String(n.src).includes('maplibre-gl'))n.remove()}))).observe(document.documentElement,{childList:true,subtree:true});setTimeout(setup,80)
})();