(()=>{
const locations=[['Hannover',52.3759,9.732],['Langenhagen',52.447,9.743],['Garbsen',52.426,9.6],['Wunstorf',52.423,9.427],['Neustadt',52.505,9.462],['Burgwedel',52.5,9.863],['Lehrte',52.375,9.98],['Burgdorf',52.447,10.006],['Laatzen',52.315,9.797],['Barsinghausen',52.3,9.46],['Springe',52.208,9.552],['Seelze',52.397,9.598],['Wedemark',52.545,9.733],['Isernhagen',52.48,9.84],['Ronnenberg',52.319,9.655],['Hemmingen',52.322,9.742],['Pattensen',52.265,9.768],['Gehrden',52.313,9.6],['Wennigsen',52.275,9.57],['Uetze',52.465,10.205]];
const center={lat:52.39,lon:9.73,z:9,tile:256};
let frames=[],index=0,timer=null;
const css=`.nativeRadar{position:absolute;inset:0;overflow:hidden;background:#dbe8ed}.nativeRadarTiles{position:absolute;inset:0}.nativeRadarTile{position:absolute;width:256px;height:256px;object-fit:cover}.nativeRadarOverlay{position:absolute;inset:0;pointer-events:none}.nativeRadarPin{position:absolute;transform:translate(-50%,-100%);background:rgba(246,243,236,.96);border:1px solid rgba(16,23,34,.2);border-radius:999px;padding:5px 8px;font:500 8px 'DM Mono';color:#101722;white-space:nowrap;box-shadow:0 5px 16px rgba(16,23,34,.18)}.nativeRadarPin:before{content:'';display:inline-block;width:6px;height:6px;border-radius:50%;background:#3976ff;margin-right:5px}.nativeRadarPin:first-child{border-color:#ff6b35}.nativeRadarRain{position:absolute;inset:0;width:100%;height:100%;object-fit:cover;image-rendering:auto;pointer-events:none}.nativeRadarBadge{position:absolute;left:16px;bottom:16px;background:rgba(246,243,236,.92);padding:9px 12px;border:1px solid rgba(16,23,34,.14);font:500 7px 'DM Mono';letter-spacing:1.5px}.nativeRadarStatus{position:absolute;right:16px;top:72px;background:rgba(246,243,236,.94);padding:8px 11px;border:1px solid rgba(16,23,34,.14);font:500 7px 'DM Mono';letter-spacing:1.2px;color:#101722}`;
const st=document.createElement('style');st.textContent=css;document.head.appendChild(st);
function world(lat,lon){const n=2**center.z,x=(lon+180)/360*n,y=(1-Math.asinh(Math.tan(lat*Math.PI/180))/Math.PI)/2*n;return{x:x*256,y:y*256}}
function init(){const el=document.getElementById('map');if(!el)return;el.innerHTML='<div class="nativeRadar"><div class="nativeRadarTiles"></div><img class="nativeRadarRain"><div class="nativeRadarOverlay"></div><div class="nativeRadarStatus">RADAR · VERBINDE…</div><div class="nativeRadarBadge">HANNOVER · RADAR LIVE</div></div>';const root=el.firstElementChild;root.__ready=true;buildBase(root);buildPins(root);loadFrames(root)}
function buildBase(root){const box=root.getBoundingClientRect(),cw=world(center.lat,center.lon),tiles=root.querySelector('.nativeRadarTiles');const cols=Math.ceil(box.width/256)+2,rows=Math.ceil(box.height/256)+2;const tx=Math.floor(cw.x/256),ty=Math.floor(cw.y/256);for(let dx=-Math.ceil(cols/2);dx<=Math.ceil(cols/2);dx++)for(let dy=-Math.ceil(rows/2);dy<=Math.ceil(rows/2);dy++){const ix=tx+dx,iy=ty+dy;if(ix<0||iy<0||ix>=2**center.z||iy>=2**center.z)continue;const img=document.createElement('img');img.className='nativeRadarTile';img.src=`https://tile.openstreetmap.org/${center.z}/${ix}/${iy}.png`;img.alt='';img.style.left=`calc(50% + ${(ix*256+128-cw.x)-128}px)`;img.style.top=`calc(50% + ${(iy*256+128-cw.y)-128}px)`;img.onerror=()=>img.remove();tiles.appendChild(img)}}
function buildPins(root){const overlay=root.querySelector('.nativeRadarOverlay'),cw=world(center.lat,center.lon);locations.forEach((p,i)=>{const w=world(p[1],p[2]),pin=document.createElement('div');pin.className='nativeRadarPin';pin.textContent=p[0];pin.style.left=`calc(50% + ${w.x-cw.x}px)`;pin.style.top=`calc(50% + ${w.y-cw.y}px)`;if(i===0)pin.style.borderColor='#ff6b35';overlay.appendChild(pin)})}
async function loadFrames(root){try{const r=await fetch('https://api.rainviewer.com/public/weather-maps.json',{cache:'no-store'});if(!r.ok)throw Error('Radar API');const j=await r.json();frames=j.radar?.past||[];if(!frames.length)throw Error('Keine Radarframes');index=frames.length-1;const input=document.getElementById('radarRange');if(input){input.max=frames.length-1;input.value=index}render(root);document.getElementById('radarPlay')?.addEventListener('click',play);input?.addEventListener('input',e=>{index=+e.target.value;render(root)});document.getElementById('radarTime').textContent='RADAR · '+new Date(frames[index].time*1000).toLocaleTimeString('de-DE',{hour:'2-digit',minute:'2-digit'});document.getElementById('radarSteps').innerHTML=frames.slice(-7).map((f,n)=>`<button class="radarStep ${n===6?'active':''}" data-r="${frames.indexOf(f)}">${new Date(f.time*1000).toLocaleTimeString('de-DE',{hour:'2-digit',minute:'2-digit'})}</button>`).join('');document.querySelectorAll('.radarStep').forEach(b=>b.onclick=()=>{index=+b.dataset.r;render(root)});root.querySelector('.nativeRadarStatus').textContent='RADAR · LIVE';}catch(e){root.querySelector('.nativeRadarStatus').textContent='RADAR · NICHT VERFÜGBAR';console.warn(e)}}
function render(root){if(!frames[index])return;const f=frames[index],img=root.querySelector('.nativeRadarRain');const n=2**center.z,w=world(center.lat,center.lon),tx=Math.floor(w.x/256),ty=Math.floor(w.y/256);const left=w.x-tx*256,top=w.y-ty*256;img.src=`https://tilecache.rainviewer.com${f.path}/512/${center.z}/${center.lat}/${center.lon}/2/1_1.png`;img.style.width='512px';img.style.height='512px';img.style.left=`calc(50% - ${left+256}px)`;img.style.top=`calc(50% - ${top+256}px)`;const rt=document.getElementById('radarTime');if(rt)rt.textContent='RADAR · '+new Date(f.time*1000).toLocaleTimeString('de-DE',{hour:'2-digit',minute:'2-digit'});document.querySelectorAll('.radarStep').forEach(b=>b.classList.toggle('active',+b.dataset.r===index))}
function play(){if(!frames.length)return;clearInterval(timer);let i=index;document.getElementById('radarPlay').textContent='Ⅱ';timer=setInterval(()=>{i=(i+1)%frames.length;index=i;const root=document.querySelector('.nativeRadar');render(root)},850);setTimeout(()=>{clearInterval(timer);document.getElementById('radarPlay').textContent='▶'},Math.min(frames.length*850,9000))}
// Prevent the optional MapLibre CDN from taking over this container; the native radar is more reliable on mobile Safari.
const observer=new MutationObserver(ms=>{for(const m of ms)for(const n of m.addedNodes){if(n.tagName==='SCRIPT'&&String(n.src).includes('maplibre-gl')){n.remove();setTimeout(init,30)}}});observer.observe(document.documentElement,{childList:true,subtree:true});
setTimeout(init,80);
})();
