(()=>{
const API='https://api.rainviewer.com/public/weather-maps.json';
const DWD='https://maps.dwd.de/geoserver/dwd/wms';
let map=null,frames=[],index=0,layer=null,playing=false,timer=null,loaded=false,apiHost='https://tilecache.rainviewer.com';
function setStatus(text){const e=document.getElementById('radarStatus');if(e)e.textContent=text}
function clock(ts){return new Date(ts*1000).toLocaleTimeString('de-DE',{hour:'2-digit',minute:'2-digit'})}
function ensureLeaflet(){return new Promise((resolve,reject)=>{if(window.L)return resolve();const css=document.createElement('link');css.rel='stylesheet';css.href='https://unpkg.com/leaflet@1.9.4/dist/leaflet.css';document.head.appendChild(css);const s=document.createElement('script');s.src='https://unpkg.com/leaflet@1.9.4/dist/leaflet.js';s.onload=resolve;s.onerror=reject;document.head.appendChild(s)})}
function initMap(){map=L.map('map',{zoomControl:true,attributionControl:true,minZoom:6,maxZoom:12,preferCanvas:true}).setView([52.39,9.73],8);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{subdomains:'abc',maxZoom:19,attribution:'© OpenStreetMap contributors'}).addTo(map);try{const dwd=L.tileLayer.wms(DWD,{layers:'dwd:Radar_rv_product_1x1km_ger',format:'image/png',transparent:true,opacity:.58,version:'1.3.0',styles:'',attribution:'DWD'});dwd.on('tileerror',()=>setStatus('RAINVIEWER · DWD NICHT ERREICHBAR'));dwd.addTo(map)}catch(e){}addMarkers()}
function addMarkers(){const P=window.WEATHER_APP?.PLACES||[];P.forEach((p,i)=>{const icon=L.divIcon({className:'',html:`<span style="display:grid;place-items:center;width:18px;height:18px;border:2px solid #fff;border-radius:50%;background:${i===0?'#d76b45':'#101820'};box-shadow:0 2px 8px #10182066;color:#fff;font:600 7px 'DM Mono',monospace">${i===0?'H':i+1}</span>`,iconSize:[18,18],iconAnchor:[9,9]});L.marker([p.lat,p.lon],{icon}).addTo(map).bindTooltip(p.name,{direction:'top',offset:[0,-8]})})}
function radarLayer(frame){const size=window.devicePixelRatio>=2?512:256;return L.tileLayer(`${apiHost}${frame.path}/${size}/{z}/{x}/{y}/2/1_1.png`,{tileSize:256,maxNativeZoom:7,maxZoom:12,opacity:0,updateWhenIdle:true,keepBuffer:3,attribution:'Weather data by RainViewer'})}
function show(i){if(!frames.length)return;index=(i+frames.length)%frames.length;const f=frames[index],next=radarLayer(f),old=layer;next.on('load',()=>{next.setOpacity(1);if(old&&map.hasLayer(old))map.removeLayer(old);layer=next;loaded=true;const t=document.getElementById('radarTime');if(t)t.textContent=`RADAR · ${clock(f.time)}`;const r=document.getElementById('radarRange');if(r){r.value=index;r.max=frames.length-1}setStatus(`LIVE · ${index+1}/${frames.length}`);if(playing)timer=setTimeout(()=>show(index+1),650)});next.on('tileerror',()=>{if(!loaded)setStatus('RADAR · KACHELFEHLER')});next.addTo(map)}
function controls(){const r=document.getElementById('radarRange'),b=document.getElementById('radarPlay');if(!r||!b)return;r.oninput=()=>{playing=false;if(timer)clearTimeout(timer);b.textContent='▶';show(+r.value)};b.onclick=()=>{playing=!playing;b.textContent=playing?'Ⅱ':'▶';if(timer)clearTimeout(timer);if(playing)show(index+1)}}
async function load(){try{await ensureLeaflet();initMap();setStatus('RADAR · VERBINDE…');const res=await fetch(API,{cache:'no-store'});if(!res.ok)throw Error('RainViewer '+res.status);const j=await res.json();apiHost=j.host||apiHost;frames=(j.radar?.past||[]).slice(-13);if(!frames.length)throw Error('Keine Radarframes');document.getElementById('radarSteps').innerHTML=frames.map(f=>`<span>${clock(f.time)}</span>`).join('');controls();show(frames.length-1);window.addEventListener('resize',()=>map.invalidateSize());setTimeout(()=>map.invalidateSize(),300)}catch(e){console.error(e);setStatus('RADAR · NICHT VERFÜGBAR');const t=document.getElementById('radarTime');if(t)t.textContent='RADAR · OFFLINE'}}
load();
})();
