(()=>{
const A=window.WEATHER_APP;
const C={clear:[0,1],cloud:[2,3],fog:[45,48],rain:[51,53,55,61,63,65,80,81,82],snow:[71,73,75],storm:[95,96,99]};
const inC=(a,c)=>a.includes(c);
const kind=c=>inC(C.storm,c)?'storm':inC(C.snow,c)?'snow':inC(C.rain,c)?'rain':inC(C.fog,c)?'fog':inC(C.cloud,c)?'cloud':'clear';
function fx(type,n=18){
 if(type==='rain')return Array.from({length:n},(_,i)=>`<i class="drop" style="--x:${(i*29)%103}%;--d:${(i%9)*.11}s;--l:${42+(i%4)*10}px"></i>`).join('')+`<i class="rainGlow"></i>`;
 if(type==='snow')return Array.from({length:14},(_,i)=>`<i class="flake" style="--x:${(i*37)%103}%;--d:${(i%7)*.55}s;--s:${5+(i%4)*2}px"></i>`).join('');
 if(type==='storm')return `<i class="stormGlow"></i><i class="bolt"></i><i class="bolt second"></i>`;
 if(type==='fog')return `<i class="mist m1"></i><i class="mist m2"></i><i class="mist m3"></i>`;
 if(type==='cloud')return `<i class="cloudShadow"></i>`;
 return `<i class="sunGlow"></i><i class="sunRay"></i>`;
}
function decorate(card,w){const art=card?.querySelector('.placeArt');if(!art)return;const type=kind(w.current.weather_code);card.classList.remove('wx-clear','wx-cloud','wx-fog','wx-rain','wx-snow','wx-storm');card.classList.add('wx-'+type);let f=art.querySelector('.weatherFx');if(!f){f=document.createElement('div');f.className='weatherFx';art.appendChild(f)}f.innerHTML=fx(type,14)}
function updateHero(w){const i=A.data.indexOf(w),card=document.querySelector(`.placeCard[data-i="${i}"]`),hero=document.querySelector('.hero');if(!hero||!card)return;const bg=card.querySelector('.placeArt')?.style.backgroundImage||'';if(bg)hero.style.backgroundImage=bg;const type=kind(w.current.weather_code);hero.classList.remove('wx-clear','wx-cloud','wx-fog','wx-rain','wx-snow','wx-storm');hero.classList.add('wx-'+type);hero.dataset.place=w.place.name;const label=card.querySelector('.cond')?.textContent?.trim()||'WECHSELHAFT';const small=document.querySelector('.heroDate small');if(small)small.textContent=`${w.place.name.toUpperCase()} · HEUTE`;const status=document.querySelector('.heroStatus small');if(status)status.textContent=`Aktuell in ${w.place.name}`;document.getElementById('heroCond').textContent=label;document.getElementById('heroTemp').textContent=Math.round(w.current.temperature_2m)+'°';document.getElementById('heroFeel').textContent=Math.round(w.current.apparent_temperature)+'°';document.getElementById('heroHum').textContent=Math.round(w.current.relative_humidity_2m)+'%';document.getElementById('heroWind').textContent=Math.round(w.current.wind_speed_10m)+' km/h';const hint=document.getElementById('hint');if(hint)hint.textContent=`${label.charAt(0)+label.slice(1).toLowerCase()} in ${w.place.name}. ${w.current.precipitation>0?'Aktuell fällt Niederschlag.':'Aktuell kein Niederschlag.'}`;const q=document.querySelector('.heroQuote');if(q)q.innerHTML=`${w.place.name}.<br>Gleicher Himmel,<br>neue Geschichten.`;let f=hero.querySelector('.heroWeatherFx');if(!f){f=document.createElement('div');f.className='heroWeatherFx';hero.appendChild(f)}f.innerHTML=fx(type,30);document.querySelectorAll('.placeCard').forEach(x=>x.classList.remove('selected'));card.classList.add('selected');window.scrollTo({top:0,behavior:'smooth'})}
function bind(){if(!A?.data?.length)return false;document.querySelectorAll('.placeCard').forEach(card=>decorate(card,A.data[+card.dataset.i]));if(!document.body.dataset.heroBound){document.body.dataset.heroBound='1';document.addEventListener('click',e=>{const card=e.target.closest('.placeCard');if(!card)return;const w=A.data[+card.dataset.i];if(w)updateHero(w)})}if(!document.body.dataset.heroReady){document.body.dataset.heroReady='1';updateHero(A.data[0])}return true}
const observer=new MutationObserver(bind);observer.observe(document.getElementById('app')||document.body,{childList:true,subtree:true});const boot=setInterval(()=>{if(bind())clearInterval(boot)},200);setTimeout(()=>clearInterval(boot),15000);
})();
