(()=>{
const A=window.WEATHER_APP;
const codes={clear:[0,1],cloud:[2,3],fog:[45,48],rain:[51,53,55,61,63,65,80,81,82],snow:[71,73,75],storm:[95,96,99]};
const has=(arr,c)=>arr.includes(c);
function kind(c){if(has(codes.storm,c))return'storm';if(has(codes.snow,c))return'snow';if(has(codes.rain,c))return'rain';if(has(codes.fog,c))return'fog';if(has(codes.cloud,c))return'cloud';return'clear'}
function particles(type,count=16){if(type==='clear')return '<i class="sunGlow"></i><i class="sunRay"></i>';if(type==='cloud')return '<i class="cloudShadow"></i><i class="cloudShadow second"></i>';if(type==='rain')return '<i class="rainGlow"></i>'+Array.from({length:count},(_,i)=>`<i class="drop" style="--i:${i};--d:${(i%7)*.14}s;--x:${(i*37)%100}%;--l:${30+(i%5)*9}px"></i>`).join('');if(type==='snow')return Array.from({length:count},(_,i)=>`<i class="flake" style="--i:${i};--d:${(i%7)*.55}s;--x:${(i*43)%100}%;--s:${5+(i%4)*2}px"></i>`).join('');if(type==='fog')return '<i class="mist m1"></i><i class="mist m2"></i><i class="mist m3"></i>';return '<i class="stormGlow"></i><i class="bolt"></i><i class="bolt second"></i>'}
function condition(w){return document.querySelector(`.placeCard[data-i="${A.data.indexOf(w)}"] .cond`)?.textContent?.trim()||'WECHSELHAFT'}
function imageFor(w){const i=A.data.indexOf(w);return window.REGION_IMAGES?.[i]||window.IMAGES?.[i]||document.querySelector(`.placeCard[data-i="${i}"] .placeArt`)?.style.backgroundImage||''}
function setHero(w){const c=w.current,art=document.querySelector('.hero'),i=A.data.indexOf(w),card=document.querySelector(`.placeCard[data-i="${i}"]`);if(!art||!card)return;const bg=imageFor(w);if(bg){const clean=bg.startsWith('url(')?bg:`url("${bg}")`;art.style.backgroundImage=clean}art.classList.remove('wx-clear','wx-cloud','wx-fog','wx-rain','wx-snow','wx-storm');art.classList.add('wx-'+kind(c.weather_code));art.dataset.place=w.place.name;const status=document.querySelector('.heroStatus small');if(status)status.textContent=`Aktuell in ${w.place.name}`;const quote=document.querySelector('.heroQuote');if(quote)quote.innerHTML=`<strong class="heroPlaceName">${w.place.name.toUpperCase()}</strong><span>Region Hannover</span>`;document.getElementById('heroCond').textContent=condition(w);document.getElementById('heroTemp').textContent=Math.round(c.temperature_2m)+'°';document.getElementById('heroFeel').textContent=Math.round(c.apparent_temperature)+'°';document.getElementById('heroHum').textContent=Math.round(c.relative_humidity_2m)+'%';document.getElementById('heroWind').textContent=Math.round(c.wind_speed_10m)+' km/h';document.getElementById('hint').textContent=`${condition(w)} in ${w.place.name}. ${c.precipitation>0?'Aktuell fällt Niederschlag.':'Aktuell kein Niederschlag.'}`;let fx=art.querySelector('.heroWeatherFx');if(!fx){fx=document.createElement('div');fx.className='heroWeatherFx';art.appendChild(fx)}fx.innerHTML=particles(kind(c.weather_code),24);document.querySelectorAll('.placeCard').forEach(x=>x.classList.remove('selected'));card.classList.add('selected');window.scrollTo({top:0,behavior:'smooth'})}
function decorate(card,w){const art=card?.querySelector('.placeArt');if(!art)return;const type=kind(w.current.weather_code);if(card.dataset.wxKind===type&&art.querySelector('.weatherFx'))return;card.classList.remove('wx-clear','wx-cloud','wx-fog','wx-rain','wx-snow','wx-storm');card.classList.add('wx-'+type);card.dataset.wxKind=type;let fx=art.querySelector('.weatherFx');if(!fx){fx=document.createElement('div');fx.className='weatherFx';art.appendChild(fx)}fx.innerHTML=particles(type,12)}
function bind(){if(!A?.data?.length)return false;document.querySelectorAll('.placeCard').forEach(card=>{const i=+card.dataset.i,w=A.data[i];if(!w)return;if(!card.dataset.motionBound){card.dataset.motionBound='1';card.addEventListener('click',()=>setHero(w))}decorate(card,w)});if(!document.querySelector('.heroWeatherFx'))setHero(A.data[0]);return true}
const observer=new MutationObserver(bind);observer.observe(document.getElementById('app')||document.body,{childList:true,subtree:true});const boot=setInterval(()=>{if(bind())clearInterval(boot)},250);setTimeout(()=>clearInterval(boot),12000);
})();