(()=>{
const A=window.WEATHER_APP;
const codes={clear:[0,1],cloud:[2,3],fog:[45,48],rain:[51,53,55,61,63,65,80,81,82],snow:[71,73,75],storm:[95,96,99]};
const has=(arr,c)=>arr.includes(c);
function kind(c){if(has(codes.storm,c))return'storm';if(has(codes.snow,c))return'snow';if(has(codes.rain,c))return'rain';if(has(codes.fog,c))return'fog';if(has(codes.cloud,c))return'cloud';return'clear'}
function particles(type,count=12){if(type==='rain')return Array.from({length:count},(_,i)=>`<i style="--i:${i};--d:${(i%5)*.18}s;--x:${(i*37)%100}%"></i>`).join('');if(type==='snow')return Array.from({length:10},(_,i)=>`<i style="--i:${i};--d:${(i%6)*.55}s;--x:${(i*43)%100}%"></i>`).join('');if(type==='storm')return `<i class="bolt"></i>`;if(type==='fog')return `<i class="fogline a"></i><i class="fogline b"></i><i class="fogline c"></i>`;return''}
function condition(w){return document.querySelector(`.placeCard[data-i="${A.data.indexOf(w)}"] .cond`)?.textContent?.trim()||'WECHSELHAFT'}
function decorate(card,w){const art=card?.querySelector('.placeArt');if(!art)return;const type=kind(w.current.weather_code);card.classList.remove('wx-clear','wx-cloud','wx-fog','wx-rain','wx-snow','wx-storm');card.classList.add('wx-'+type);let fx=art.querySelector('.weatherFx');if(!fx){fx=document.createElement('div');fx.className='weatherFx';art.appendChild(fx)}fx.innerHTML=particles(type)}
function updateHero(w){const c=w.current,art=document.querySelector('.hero'),i=A.data.indexOf(w),card=document.querySelector(`.placeCard[data-i="${i}"]`);if(!art||!card)return;const bg=card.querySelector('.placeArt')?.style.backgroundImage||'';if(bg)art.style.backgroundImage=bg;art.classList.remove('wx-clear','wx-cloud','wx-fog','wx-rain','wx-snow','wx-storm');art.classList.add('wx-'+kind(c.weather_code));art.dataset.place=w.place.name;document.querySelector('.heroStatus small').textContent=`Aktuell in ${w.place.name}`;document.getElementById('heroCond').textContent=condition(w);document.getElementById('heroTemp').textContent=Math.round(c.temperature_2m)+'°';document.getElementById('heroFeel').textContent=Math.round(c.apparent_temperature)+'°';document.getElementById('heroHum').textContent=Math.round(c.relative_humidity_2m)+'%';document.getElementById('heroWind').textContent=Math.round(c.wind_speed_10m)+' km/h';document.getElementById('hint').textContent=`${condition(w)} in ${w.place.name}. ${c.precipitation>0?'Aktuell fällt Niederschlag.':'Aktuell kein Niederschlag.'}`;let fx=art.querySelector('.heroWeatherFx');if(!fx){fx=document.createElement('div');fx.className='heroWeatherFx';art.appendChild(fx)}fx.innerHTML=particles(kind(c.weather_code),22);document.querySelectorAll('.placeCard').forEach(x=>x.classList.remove('selected'));card.classList.add('selected');window.scrollTo({top:0,behavior:'smooth'})}
function bind(){if(!A?.data?.length)return false;document.querySelectorAll('.placeCard').forEach(card=>{const i=+card.dataset.i,w=A.data[i];if(!w)return;if(!card.dataset.motionBound){card.dataset.motionBound='1';card.addEventListener('click',()=>updateHero(w))}decorate(card,w)});if(!document.querySelector('.heroWeatherFx'))updateHero(A.data[0]);return true}
const observer=new MutationObserver(bind);observer.observe(document.getElementById('app')||document.body,{childList:true,subtree:true});const boot=setInterval(()=>{if(bind())clearInterval(boot)},250);setTimeout(()=>clearInterval(boot),12000);
})();
